sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abhighosh18/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true abhighosh18/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-west-2-244181945186"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
