sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abhighosh18/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true abhighosh18/docker-react-app npm run test -- --coverage
